name: Go

on:
  push:
    branches: gh-action

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: make tools

    - name: Test
      run: make test

    - name: Get dist list
      run: go tool dist list
      
    - name: Build
      run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o terraform-provider-nutanix

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-provider-nutanix
        path: terraform-provider-nutanix
